### ISSUE TITLE
Hub requiring auth - not supported? Or WSS issue?

### ISSUE THREAD

**Issue by cbdelavenne** [TargetProcess/signalr-client-py#12]
Hello,

Firstly, glad to see signalr-client-py ported to Python 3.

That said, I'm trying to connect to a signalr hub that requires authentication.
It works up to a point, but then it fails the actually start connection during the handshake.

Code extract:
```
with Session() as session:
    session.headers.update({'Authorization': 'Bearer {tok}'.format(tok=token)})

    # Create a connection
    connection = Connection(signalr_url, session)

    # get notifications hub
    notifications = connection.register_hub('NotificationsHub')

    # start connection
    connection.start()
```
Traceback:
```
Traceback (most recent call last):
  File "/Users/cbdelavenne/workspace/LANDR.Python-Standalone/signalr-client-poc.py", line 27, in <module>
    connection.start()
  File "/Users/cbdelavenne/.virtualenv/python3.5-LANDR.PySA/lib/python3.5/site-packages/signalr/_connection.py", line 49, in start
    listener = self.__transport.start()
  File "/Users/cbdelavenne/.virtualenv/python3.5-LANDR.PySA/lib/python3.5/site-packages/signalr/transports/_auto_transport.py", line 28, in start
    return self.__transport.start()
  File "/Users/cbdelavenne/.virtualenv/python3.5-LANDR.PySA/lib/python3.5/site-packages/signalr/transports/_ws_transport.py", line 35, in start
    enable_multithread=True)
  File "/Users/cbdelavenne/.virtualenv/python3.5-LANDR.PySA/lib/python3.5/site-packages/websocket/_core.py", line 105, in create_connection
    websock.connect(url, **options)
  File "/Users/cbdelavenne/.virtualenv/python3.5-LANDR.PySA/lib/python3.5/site-packages/websocket/_core.py", line 272, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/Users/cbdelavenne/.virtualenv/python3.5-LANDR.PySA/lib/python3.5/site-packages/websocket/_handshake.py", line 67, in handshake
    status, resp = _get_resp_headers(sock)
  File "/Users/cbdelavenne/.virtualenv/python3.5-LANDR.PySA/lib/python3.5/site-packages/websocket/_handshake.py", line 123, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d", status)
websocket._exceptions.WebSocketBadStatusException: Handshake status 400
```
I stepped through it all, and I wasn't able to effectively determine the problem.
Thoughts?

**Comment by u-abramchuk** [comment]
Hi cbdelavenne,

thank you for reporting the issue.

**Comment by u-abramchuk** [comment]
Fixed in version 0.0.7

**Comment by cbdelavenne** [comment]
@u-abramchuk  can you release 0.0.7 on PyPi? Thank you!

**Comment by cbdelavenne** [comment]
@u-abramchuk Still getting the same error with a valid Bearer token. Thoughts?

**Comment by u-abramchuk** [comment]
Hi cbdelavenne!

Sorry to hear that. The only thing that comes to my mind now is to check Python version. While I was working on version 0.0.7 I've faced an issue that old Python versions (like 2.7.6) don't support TLS 1.2 and I've got errors similar to the one you've provided.

Does this sample work without Basic auth?

Please let me know if that helped.

**Comment by denisvolokh** [comment]
Hi,

Did you manage to solve this problem? I have the same issue with authentication.
